### ISSUE TITLE
Hashcons module_path?

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/lambdapi#24]
https://github.com/rlepigre/lambdapi/blob/561b959f55ebc8ce397dd6a433964f1b214f7de8/src/sign.ml#L74

**Comment by fblanqui** [comment]
module_path comparison is also used in unlink

**Comment by rlepigre** [comment]
I'm pretty sure that there is nothing we can do for the `link` function. Indeed, we read an object file using the Marshal module, so we have no way of forcing the contained module paths to be physically equal. Ensuring this would lead to less efficient code as we would need another pass, using comparison anyway.

For `unlink` this is not really important either since this code is only used when producing an object file, which is not a bottleneck for efficiency.

What is really important with `link` and `unlink` is that we establish physical equality on symbols. This really makes things more efficient when comparing terms. And this is also very important to ensure that all reduction rules regarding a given symbol are stored in this symbol in a unique structure.

**Comment by fblanqui** [comment]
Right. I didn't think about this Marshal thing.

**Comment by fblanqui** [comment]
If I understand correctly, unlink is not necessary. It's just a way to reduce the size of object files. Link will reset the types anyway. Could you please add more detailed comments about this?

**Comment by rlepigre** [comment]
Exactly. I improved the comments in 8780075447d8cb7aa35c95219e40fd23a2330a6d.
