### ISSUE TITLE
Performance problem and memory usage

### ISSUE THREAD

**Issue by rlepigre** [rlepigre/lambdapi#47]
The current implementation performs very badly in terms of memory usage, and this has big consequences on speed. The problem (at least part of it) comes from the new type-checking / inference functions, which allocates a lot of memory.

One possibility for improvement would be to type-check using a stack (pushing the arguments until a head term is found) to avoid introducing too many unification variables. We should also avoid situations where terms are copied (this breaks physical equalities).

**Comment by fblanqui** [comment]
It also seems that metas are always added into all_metas and never removed. Outside proof mode, all_metas should be cleared after each command. In proof mode, all_metas should be part of the global state of the system and managed with Timed. The global state should be saved before each command, and restored after its completion.

Moreover, when a meta is instantiated, we could set its type to a dummy constant/None because it will never be used anymore (because of unfold). This could free a little bit of memory during the completion of a command.

**Comment by rlepigre** [comment]
On instantiation, metavariables are removed from ``all_metas`` here:
https://github.com/rlepigre/lambdapi/blob/b635d354f088084804ee025b4e91151272b540f1/src/solve.ml#L116-L117
