### ISSUE TITLE
Allows redundant parenthesis

### ISSUE THREAD

**Issue by francoisthire** [rlepigre/lambdapi#53]
It should be nice that the following program could be parsed:

```
A : Type.

foo : (x : A) -> A.
```

**Comment by rlepigre** [comment]
I think we already had a discussion about that, and I really don't think that having several syntaxes for the same thing is helpful. We can either choose `x:A -> B` or `(x:A) -> B`, but I am strongly against having both.

Anyway, we plan to have a big discussion about syntax, because the Dedukti syntax is not great (to say the least).

**Comment by rlepigre** [comment]
Won't fix.
